# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-08-06 08:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', models.CharField(max_length=256)),
                ('exercise_key', models.CharField(max_length=1024)),
                ('lang', models.CharField(max_length=8)),
                ('submission_meta', django.contrib.postgres.fields.jsonb.JSONField()),
                ('container_ref', models.CharField(max_length=128, unique=True)),
                ('container_state', models.CharField(choices=[('c', 'CREATED'), ('o', 'ORDERED'), ('s', 'SCHEDULED'), ('r', 'RUNNING'), ('f', 'COMPLETED')], default='c', max_length=1)),
                ('upload_url', models.URLField()),
                ('upload_state', models.CharField(choices=[('p', 'PENDING'), ('s', 'SCHEDULED'), ('o', 'SUCCEEDED'), ('f', 'FAILED')], default='p', max_length=1)),
                ('upload_state_updated', models.DateTimeField(null=True)),
                ('upload_code', models.PositiveSmallIntegerField(default=0)),
                ('upload_attempt', models.PositiveSmallIntegerField(default=0)),
                ('upload_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
